name: Create and publish Docker Image

on:
  workflow_call:
    inputs:
      image_name:
        required: true
        type: string
      tag: 
        type: string
    secrets:
      registery_userame:
        required: true
      registery_password:
        required: true
        
jobs:
    build:
     runs-on: ubuntu-latest
     steps:
      - uses: actions/checkout@v2
      
      - name: Setup BuildX
        uses: docker/setup-buildx-action@v2.0.0
        
      - name: Login to the Registry
        uses: docker/login-action@v2.0.0
        with:
          username: ${{secrets.registry_username}}
          password: ${{secrets.registry_password}}
          
      - name: Build and Push the Image
        uses: docker/build-push-action@v3.0.0
        with:
          context: _
          push: true

  
