name: Chained workflow 1

# Controls when the workflow will run
on:
  workflow_call:
    inputs:
      version:
        description: 'Version tag used for the deployment'
        default: 'v0.0.0'
        required: true
        type: string
    secrets:
      credentials:
        description: 'A secret containing credentials'
        required: false


          

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  job_workflow_1:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a set of commands using the runners shell
      - name: Run a single line script
        run: |
          echo "Hello World"
